signet=1
fallbackfee=0.0001
server=1

[signet]
rpcuser=teste
rpcpassword=teste
rpcallowip=127.0.0.1
rpcbind=127.0.0.1
port=58445
rpcport=58443

zmqpubrawtx=tcp://127.0.0.1:58331
zmqpubrawblock=tcp://127.0.0.1:58334
zmqpubhashblock=tcp://127.0.0.1:58335

debug=zmq